"""Initial migration: Create Exercise, Workout, and WorkoutExercise models

Revision ID: f2b2f4b90951
Revises: 
Create Date: 2026-04-22 20:51:36.068700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b2f4b90951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('equipment_needed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(name) > 0', name='ck_exercise_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category', name='uq_exercise_name_category')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('duration_minutes > 0', name='ck_workout_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds > 0', name='ck_workout_exercise_duration_positive'),
    sa.CheckConstraint('reps > 0 OR sets > 0 OR duration_seconds > 0', name='ck_workout_exercise_has_data'),
    sa.CheckConstraint('reps IS NULL OR reps > 0', name='ck_workout_exercise_reps_positive'),
    sa.CheckConstraint('sets IS NULL OR sets > 0', name='ck_workout_exercise_sets_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
